//NEXT JS
import type { Metadata } from "next";
import { Inter, Barlow, Geist } from "next/font/google";

//Global css
import "./globals.css";
import { cn } from "@/lib/utils";

//Theme Provider
import { ThemeProvider } from "next-themes";

//CLERK PROVIDER
import { ClerkProvider } from '@clerk/nextjs'

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  subsets: ["latin"],
});

const barlowFont = Barlow({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "GoShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider>
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(geist.variable, barlowFont.variable)}
    >
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
